services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    platform: linux/amd64
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: zaperfy
      MB_DB_PASS: zaperfy@q1w2e3r4
      MB_DB_HOST: host.docker.internal
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5